Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /dj-rest-auth/registration/account-confirm-email/<key>/
Bad Request: /dj-rest-auth/registration/account-confirm-email/<key>/
Watching for file changes with StatReloader
Disabling user: test
Internal Server Error: /dj-rest-auth/registration/account-confirm-email/NA:1tXGBw:lI-VzhrdeUMkGqA7rnjnEhnngam_ZVp-TQyj3QN-_rA/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 227, in get
    return self.render_to_response(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 200, in render_to_response
    template=self.get_template_names(),
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 212, in get_template_names
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: TemplateResponseMixin requires either a definition of 'template_name' or an implementation of 'get_template_names()'
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Bad Request: /dj-rest-auth/registration/account-confirm-email/<key>/
Disabling user: test
Internal Server Error: /dj-rest-auth/registration/account-confirm-email/NQ:1tXGPw:FGc29rgdrpuSHqQsZroQuFnIRbq6QfODoQeo7K0m7Ns/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 227, in get
    return self.render_to_response(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 200, in render_to_response
    template=self.get_template_names(),
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 212, in get_template_names
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: TemplateResponseMixin requires either a definition of 'template_name' or an implementation of 'get_template_names()'
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
Disabling user: test
Internal Server Error: /dj-rest-auth/registration/account-confirm-email/Ng:1tXGaD:rF04UgiAx9GKSos0gpAoal1LCOio0JJQdbJX1H62g-A/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 227, in get
    return self.render_to_response(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 200, in render_to_response
    template=self.get_template_names(),
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 212, in get_template_names
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: TemplateResponseMixin requires either a definition of 'template_name' or an implementation of 'get_template_names()'
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\signals.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /dj-rest-auth/registration/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 47, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 68, in create
    user = self.perform_create(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 84, in perform_create
    user = serializer.save(self.request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\serializers.py", line 279, in save
    setup_user_email(request, user, [])
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\utils.py", line 254, in setup_user_email
    assert not EmailAddress.objects.filter(user=user).exists()  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Internal Server Error: /dj-rest-auth/registration/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 47, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 68, in create
    user = self.perform_create(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 84, in perform_create
    user = serializer.save(self.request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\serializers.py", line 279, in save
    setup_user_email(request, user, [])
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\utils.py", line 254, in setup_user_email
    assert not EmailAddress.objects.filter(user=user).exists()  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Internal Server Error: /dj-rest-auth/registration/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 47, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 68, in create
    user = self.perform_create(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 84, in perform_create
    user = serializer.save(self.request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\serializers.py", line 279, in save
    setup_user_email(request, user, [])
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\utils.py", line 254, in setup_user_email
    assert not EmailAddress.objects.filter(user=user).exists()  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Bad Request: /dj-rest-auth/registration/
Internal Server Error: /dj-rest-auth/registration/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 47, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 68, in create
    user = self.perform_create(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 84, in perform_create
    user = serializer.save(self.request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\serializers.py", line 279, in save
    setup_user_email(request, user, [])
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\utils.py", line 254, in setup_user_email
    assert not EmailAddress.objects.filter(user=user).exists()  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /dj-rest-auth/registration/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 47, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 68, in create
    user = self.perform_create(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\views.py", line 84, in perform_create
    user = serializer.save(self.request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\registration\serializers.py", line 279, in save
    setup_user_email(request, user, [])
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\utils.py", line 254, in setup_user_email
    assert not EmailAddress.objects.filter(user=user).exists()  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\signals.py changed, reloading.
Watching for file changes with StatReloader
Disabling user: test
Internal Server Error: /dj-rest-auth/registration/account-confirm-email/MTM:1tXHGG:EttA9jgEMXmN6aWTVgJ2qHhdreWlKCGJXdn0zzi0zog/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 227, in get
    return self.render_to_response(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 200, in render_to_response
    template=self.get_template_names(),
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 212, in get_template_names
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: TemplateResponseMixin requires either a definition of 'template_name' or an implementation of 'get_template_names()'
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /dj-rest-auth/registration/
Bad Request: /dj-rest-auth/registration/
Bad Request: /dj-rest-auth/registration/
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
Method Not Allowed: /dj-rest-auth/registration/
Disabling user: test
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
Disabling user: test
Disabling user: test
Disabling user: test
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Disabling user: test
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
Disabling user: test
Disabling user: test
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
Disabling user: Test
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
Disabling user: test
Not Found: /login
Not Found: /login
Internal Server Error: /dj-rest-auth/registration/account-confirm-email/MjI:1tXJoB:joirxFfdEkemAegB5zO-OtqauOHpceG2hH_r-oKZ02w/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py", line 28, in get
    confirmation = self.get_object()
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\views.py", line 300, in get_object
    raise Http404()
django.http.response.Http404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py", line 45, in get
    return render(request, self.template_name, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\base.py", line 573, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 9: 'static'. Did you forget to register or load this tag?
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /dj-rest-auth/registration/account-confirm-email/MjI:1tXJoB:joirxFfdEkemAegB5zO-OtqauOHpceG2hH_r-oKZ02w/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py", line 28, in get
    confirmation = self.get_object()
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\views.py", line 300, in get_object
    raise Http404()
django.http.response.Http404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py", line 45, in get
    return render(request, self.template_name, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\template\base.py", line 573, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 9: 'static'. Did you forget to register or load this tag?
Not Found: /login
Not Found: /login
Not Found: /login
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\urls.py changed, reloading.
Watching for file changes with StatReloader
Disabling user: test
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\views.py changed, reloading.
Watching for file changes with StatReloader
Disabling user: test
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\config\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /dj-rest-auth/login/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: project_customuser

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\views.py", line 48, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\views.py", line 125, in post
    self.serializer.is_valid(raise_exception=True)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\serializers.py", line 445, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\serializers.py", line 121, in validate
    user = self.get_auth_user(username, email, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\serializers.py", line 97, in get_auth_user
    return self.get_auth_user_using_allauth(username, email, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\serializers.py", line 63, in get_auth_user_using_allauth
    return self._validate_email(email, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\serializers.py", line 31, in _validate_email
    user = self.authenticate(email=email, password=password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\serializers.py", line 27, in authenticate
    return authenticate(self.context['request'], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 79, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\auth_backends.py", line 18, in authenticate
    ret = self._authenticate_by_email(**credentials)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\auth_backends.py", line 61, in _authenticate_by_email
    users = filter_users_by_email(email, prefer_verified=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\utils.py", line 346, in filter_users_by_email
    mails = list(EmailAddress.objects.filter(email=email).select_related("user"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: project_customuser
Internal Server Error: /dj-rest-auth/login/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: project_customuser

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\views.py", line 48, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\views.py", line 125, in post
    self.serializer.is_valid(raise_exception=True)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\serializers.py", line 445, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\serializers.py", line 121, in validate
    user = self.get_auth_user(username, email, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\serializers.py", line 97, in get_auth_user
    return self.get_auth_user_using_allauth(username, email, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\serializers.py", line 63, in get_auth_user_using_allauth
    return self._validate_email(email, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\serializers.py", line 31, in _validate_email
    user = self.authenticate(email=email, password=password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\serializers.py", line 27, in authenticate
    return authenticate(self.context['request'], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 79, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\auth_backends.py", line 18, in authenticate
    ret = self._authenticate_by_email(**credentials)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\auth_backends.py", line 61, in _authenticate_by_email
    users = filter_users_by_email(email, prefer_verified=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\utils.py", line 346, in filter_users_by_email
    mails = list(EmailAddress.objects.filter(email=email).select_related("user"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: project_customuser
Internal Server Error: /dj-rest-auth/login/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: project_customuser

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\views.py", line 48, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\views.py", line 125, in post
    self.serializer.is_valid(raise_exception=True)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\rest_framework\serializers.py", line 445, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\serializers.py", line 121, in validate
    user = self.get_auth_user(username, email, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\serializers.py", line 97, in get_auth_user
    return self.get_auth_user_using_allauth(username, email, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\serializers.py", line 63, in get_auth_user_using_allauth
    return self._validate_email(email, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\serializers.py", line 31, in _validate_email
    user = self.authenticate(email=email, password=password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\dj_rest_auth\serializers.py", line 27, in authenticate
    return authenticate(self.context['request'], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 79, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\auth_backends.py", line 18, in authenticate
    ret = self._authenticate_by_email(**credentials)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\auth_backends.py", line 61, in _authenticate_by_email
    users = filter_users_by_email(email, prefer_verified=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\allauth\account\utils.py", line 346, in filter_users_by_email
    mails = list(EmailAddress.objects.filter(email=email).select_related("user"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: project_customuser
Internal Server Error: /admin/auth/user/
Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: project_customuser

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 260, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 229, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 202, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 37, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 17, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 216, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\contrib\auth\backends.py", line 157, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: project_customuser
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\migrations\0001_initial.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\migrations\0001_initial.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /admin/auth/user/
Bad Request: /dj-rest-auth/login/
C:\Users\Ramon\OneDrive\Dokumente\GitHub\pp5-paw_buddy\backend\project\admin.py changed, reloading.
Watching for file changes with StatReloader
Method Not Allowed: /dj-rest-auth/registration/
Disabling user: test
Unauthorized: /dj-rest-auth/user/
Unauthorized: /dj-rest-auth/user/
